# Generated by Django 5.0.1 on 2024-02-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
