# Generated by Django 5.0.1 on 2024-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialresource',
            name='usage_mode',
            field=models.CharField(choices=[('Partagée', 'P'), ('Exclusif', 'E')], max_length=10),
        ),
    ]
