# Generated by Django 5.0.1 on 2024-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_materialresource_usage_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialresource',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingreport',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='object',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='summaryreport',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
