# Generated by Django 5.0.1 on 2024-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_task_material_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='material_resources',
            field=models.ManyToManyField(to='project.materialresource'),
        ),
    ]
