# Generated by Django 5.0.1 on 2024-02-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_task_material_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(related_name='taks_todo', to='project.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='project.team'),
        ),
    ]
