# Generated by Django 5.0.1 on 2024-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_team_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Cahier de charges', 'CD'), ('Document de conception', 'DC'), ('Code source', 'CS'), ('Code exécutable', 'CE'), ('Rapport de test', 'RT'), ('Manuel', 'MA')], max_length=30),
        ),
    ]
